server:
  port: 8084

spring:
  application:
    name: webtrack-notification
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

notification:
  from: "no-reply@webtrack.local"

kafka:
  topics:
    allocation-events: allocation-events
    leave-events: leave-events
    timelog-events: timelog-events
